import { type ReactNode } from 'react';
import type { Metadata } from 'next';
import { App } from '../components/App/App';

export const metadata: Metadata = {
	title: 'AgDS Starter Kit',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<App>{children}</App>
			</body>
		</html>
	);
}
